manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
    - name: hydro8
      url-base: https://github.com/Hydro8
    - name: keebs34
      url-base: https://github.com/keebs34
    - name: pfilipp
      url-base: https://github.com/pfilipp
  projects:
    - name: zmk-config-selenium
      remote: keebs34
      revision: main
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-behavior-runtime-sensor-rotate
      remote: cormoran
      revision: main
    - name: zmk-module-ble-management
      remote: cormoran
      revision: main
    - name: zmk-module-battery-history
      remote: cormoran
      revision: main
    - name: zmk-module-runtime-input-processor
      remote: cormoran
      revision: main
    - name: zmk-dongle-display
      remote: hydro8
      revision: main
    - name: zmk-layer
      remote: pfilipp
      revision: main
  self:
    path: config
