name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  extract-dts-pre:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gettext cmake git \
            gcc-arm-none-eabi device-tree-compiler
          pip3 install west

      - name: West Init
        run: west init -l config

      - name: West Update
        timeout-minutes: 15
        run: west update || west update
        
      - name: Build Dongle
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
          GNUARMEMB_TOOLCHAIN_PATH: /usr
        run: west build -b nice_nano@2 --pristine -s modules/zmk/app -- -DZMK_CONFIG=config -DSHIELD=eyelash_sofle_central_dongle -DSHIELD=dongle_display -DSHIELD=raw_hid_adapter

      - name: Upload dts.pre
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dts-pre
          path: build/zephyr/zephyr.dts.pre